### ISSUE TITLE
🤷‍♂️

### ISSUE THREAD

**Issue by WTSTiNy** [LilForkHatesYou/Okuru-Selfbot#3]
"Webhooks": {
        "DM Logger": "https://discord.com/api/webhooks/876820452507545691/TWqMp8ymdlMoculSsc6ozq-09V5aYvECIoVSAtgLFVoXxY0JmPA797vi0B1wYliplWQi",
        "Nitro Logger": "https://discord.com/api/webhooks/876820452507545691/TWqMp8ymdlMoculSsc6ozq-09V5aYvECIoVSAtgLFVoXxY0JmPA797vi0B1wYliplWQi",
        "GC Logger": "https://discord.com/api/webhooks/876820452507545691/TWqMp8ymdlMoculSsc6ozq-09V5aYvECIoVSAtgLFVoXxY0JmPA797vi0B1wYliplWQi",
        "Giveaway Logger": "https://discord.com/api/webhooks/876820452507545691/TWqMp8ymdlMoculSsc6ozq-09V5aYvECIoVSAtgLFVoXxY0JmPA797vi0B1wYliplWQi",
        "Info Logger": "https://discord.com/api/webhooks/876820452507545691/TWqMp8ymdlMoculSsc6ozq-09V5aYvECIoVSAtgLFVoXxY0JmPA797vi0B1wYliplWQi",
        "Admin Logger": "https://discord.com/api/webhooks/876820452507545691/TWqMp8ymdlMoculSsc6ozq-09V5aYvECIoVSAtgLFVoXxY0JmPA797vi0B1wYliplWQi"
    }

File: config.json

Lines: 21-28

**Comment by LilForkHatesYou** [comment]
Those are Gowixx's webhooks?

**Comment by WTSTiNy** [comment]
...
